### PR TITLE
Adding types

### PR DESCRIPTION
**Pull request by ignaciolarranaga**
Hope it is useful, types.

### CODE REVIEW

**Comment by ukch** [comment]
@ignaciolarranaga Why did you close this PR?

**Comment by seeden** [comment]
because the new version will be in TypeScript

**Comment by ukch** [comment]
@seeden Just out of interest, is the new version far off? Do you have any beta version or anything yet?

**Comment by seeden** [comment]
2 weeks

**Comment by dunklesToast** [comment]
So any Update on this? Having no typings sucks and there's still no beta or full release of this script with types.

**Pull request closed without merging**
